### ISSUE TITLE
:add and :del freezes curses interface

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-curses#26] opened 2015-06-19 16:14 UTC
I accidently used empty :del and the feed where the cursor was got removed and the curses interface unresponsive. (Items of the deleted feed still visible, but no interaction possible)

Tried then :add $URLFORAFEED and noticed similar behaviour. (curses freezed. After killing and restarting the new feed was displayed)

Log from canto-curses -v + killall SIGUSR1

>18:03:24 : CANTO-CURSES -> 

>LOCKS:  
NAME: Thread-2
FILE: "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
  self._bootstrap_inner()
FILE: "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
  self.run()
FILE: "/usr/lib/python3.4/threading.py", line 868, in run
  self._target(*self._args, **self._kwargs)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/subthread.py", line 57, in pthread
  r = self.read()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/subthread.py", line 48, in read
  r = self.backend.do_read(self.conn)
FILE: "/usr/lib/python3.4/site-packages/canto_next/protocol.py", line 224, in do_read
  r = self._do_read(conn, timeout)
FILE: "/usr/lib/python3.4/site-packages/canto_next/protocol.py", line 244, in _do_read
  p = poll.poll(timeout)
18:03:24 : CANTO-CURSES -> 

>LOCKS:  
NAME: Thread-1
FILE: "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
  self._bootstrap_inner()
FILE: "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
  self.run()
FILE: "/usr/lib/python3.4/threading.py", line 868, in run
  self._target(*self._args, **self._kwargs)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/subthread.py", line 57, in pthread
  r = self.read()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/subthread.py", line 48, in read
  r = self.backend.do_read(self.conn)
FILE: "/usr/lib/python3.4/site-packages/canto_next/protocol.py", line 224, in do_read
  r = self._do_read(conn, timeout)
FILE: "/usr/lib/python3.4/site-packages/canto_next/protocol.py", line 244, in _do_read
  p = poll.poll(timeout)
18:03:24 : CANTO-CURSES -> 

>LOCKS:  
NAME: Thread-4
FILE: "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
  self._bootstrap_inner()
FILE: "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
  self.run()
FILE: "/usr/lib/python3.4/threading.py", line 868, in run
  self._target(*self._args, **self._kwargs)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/gui.py", line 194, in run
  self.callbacks["set_var"]("info_msg", "")
FILE: "/usr/lib/python3.4/site-packages/canto_curses/config.py", line 953, in set_var
  call_hook("curses_var_change", [{ tweak : value }])
FILE: "/usr/lib/python3.4/site-packages/canto_next/hooks.py", line 50, in call_hook
  func(*args)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/text.py", line 222, in on_var_change
  self.cmd_destroy()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/text.py", line 227, in cmd_destroy
  TextBox.cmd_destroy(self)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/guibase.py", line 96, in cmd_destroy
  self.callbacks["die"](self)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/screen.py", line 519, in die_callback
  sync_lock.acquire_write()
FILE: "/usr/lib/python3.4/site-packages/canto_next/rwlock.py", line 85, in acquire_write
  r = self.lock.acquire(block)
18:03:24 : CANTO-CURSES -> 

>LOCKS:  
NAME: MainThread
FILE: "/usr/bin/canto-curses", line 7, in <module>
  c = CantoCurses()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/main.py", line 290, in __init__
  self.start()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/main.py", line 276, in start
  self.run()
FILE: "/usr/lib/python3.4/site-packages/canto_curses/main.py", line 228, in run
  time.sleep(1)
FILE: "/usr/lib/python3.4/site-packages/canto_curses/main.py", line 148, in sigusr1
  for filename, lineno, fname, line in traceback.extract_stack(stack):
18:03:24 : CANTO-CURSES -> 

>STACKS:
18:03:24 : CANTO-CURSES -> Lock global sync lock (0 readers)
18:03:24 : CANTO-CURSES -> Lock writer (thread -1255146688):
18:03:24 : CANTO-CURSES ->   File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/canto_curses/gui.py", line 242, in run_gui
    sync_lock.acquire_write()
  File "/usr/lib/python3.4/site-packages/canto_next/rwlock.py", line 90, in acquire_write
    self.writer_stacks.append(traceback.format_stack())

>18:03:24 : CANTO-CURSES -> Lock global sync lock (0 readers)
18:03:24 : CANTO-CURSES -> Lock writer (thread -1255146688):
18:03:24 : CANTO-CURSES ->   File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/canto_curses/gui.py", line 244, in run_gui
    self.glog_handler.flush_deferred_logs()
  File "/usr/lib/python3.4/site-packages/canto_curses/gui.py", line 52, in flush_deferred_logs
    self._emit("info_msg", InfoBox, record)
  File "/usr/lib/python3.4/site-packages/canto_curses/gui.py", line 37, in _emit
    self.screen.add_window_callback(window_type)
  File "/usr/lib/python3.4/site-packages/canto_curses/screen.py", line 571, in add_window_callback
    sync_lock.acquire_write()
  File "/usr/lib/python3.4/site-packages/canto_next/rwlock.py", line 90, in acquire_write
    self.writer_stacks.append(traceback.format_stack())

>18:03:24 : CANTO-CURSES -> VARS: {'needs_redraw': True, 'info_msg': '', 'reader_offset': 0, 'reader_item': None, 'taglist_visible_tags': [[<canto_curses.story.Story object at 0xb5eb62cc>, <canto_curses.story.Story object at 0xb5eb650c>, <canto_curses.story.Story object at 0xb5eb66cc>], [<canto_curses.story.Story object at 0xb5e9620c>], [<canto_curses.story.Story object at 0xb5e96b0c>, <canto_curses.story.Story object at 0xb5e96c4c>, <canto_curses.story.Story object at 0xb5e96ccc>, <canto_curses.story.Story object at 0xb5e96e0c>], [<canto_curses.story.Story object at 0xb5eb8cac>, <canto_curses.story.Story object at 0xb5eb8e2c>, <canto_curses.story.Story object at 0xb5eb8f8c>, <canto_curses.story.Story object at 0xb5eb8e4c>, <canto_curses.story.Story object at 0xb5eb890c>, <canto_curses.story.Story object at 0xb54c84ec>], [<canto_curses.story.Story object at 0xb5ea23cc>]], 'strtags': ['maintag:Golem.de', 'maintag:Heise', 'maintag:Stuttmann', 'maintag:Techerator', 'maintag:Spiegel', 'maintag:BBC', 'maintag:Phoronix', 'maintag:Techdirt.', 'maintag:Pro-Linux', 'maintag:Planet Arch Linux', 'maintag:Planet Arch Linux De', 'maintag:Arch Linux Bugtracker::', 'maintag:Canto', 'maintag:BITblokes', 'maintag:Inconsolation', 'maintag:Motho ke motho ka botho', 'maintag:Neusprech', 'maintag:Niggemeier', 'maintag:Slate Star Codex', 'maintag:TekSec', 'maintag:Schneier on Security', 'maintag:Mostly signs (some portents)', 'maintag:The Legal Satyricon'], 'error_msg': 'No error.', 'needs_resize': False, 'target_offset': 15, 'target_obj': <canto_curses.story.Story object at 0xb54c8b4c>, 'input_do_completions': True, 'selected': <canto_curses.story.Story object at 0xb54c8b4c>, 'input_prompt': '', 'input_completion_root': '', 'input_completions': [], 'location': [], 'curtags': ['maintag:Golem.de', 'maintag:Heise', 'maintag:Stuttmann', 'maintag:Techerator', 'maintag:Spiegel', 'maintag:BBC', 'maintag:Phoronix', 'maintag:Techdirt.', 'maintag:Pro-Linux', 'maintag:Planet Arch Linux', 'maintag:Planet Arch Linux De', 'maintag:Arch Linux Bugtracker::', 'maintag:Canto', 'maintag:BITblokes', 'maintag:Inconsolation', 'maintag:Motho ke motho ka botho', 'maintag:Neusprech', 'maintag:Niggemeier', 'maintag:Slate Star Codex', 'maintag:TekSec', 'maintag:Schneier on Security', 'maintag:Mostly signs (some portents)', 'maintag:The Legal Satyricon'], 'transforms': [], 'needs_refresh': True, 'dispel_msg': False, 'infobox_offset': 0, 'errorbox_offset': 0}
18:03:24 : CANTO-CURSES -> OPTS: {'kill_daemon_on_exit': False, 'main': {'key': {'?': 'help', ':': 'command', '\\': 'update', 'f5': 'update', 'C-r': 'refresh', 'q': 'quit'}}, 'update': {'auto': {'interval': 20, 'enabled': False}, 'style': 'append'}, 'reader': {'enumerate_links': False, 'key': {'l': 'show-links', 'up': 'scroll-up', 'j': 'scroll-down', 'g': 'goto', 'space': 'destroy', 'k': 'scroll-up', 'down': 'scroll-down', 'p': 'destroy & prev-item & item-state read & reader', 'n': 'destroy & next-item & item-state read & reader', 'N': 'destroy & next-tag & item-state read & reader', 'npage': 'page-down', 'e': 'show-enclosures', 'P': 'destroy & prev-tag & item-state read & reader', 'ppage': 'page-up', 's': 'show-summary'}, 'show_description': True, 'show_enclosures': True, 'window': {'align': 'topleft', 'border': 'smart', 'float': True, 'maxheight': 0, 'maxwidth': 0}}, 'browser': {'text': False, 'path': ' xdg-open %u'}, 'errorbox': {'key': {'up': 'scroll-up', 'space': 'destroy', 'ppage': 'page-up', 'npage': 'page-down', 'down': 'scroll-down'}, 'window': {'align': 'topleft', 'border': 'full', 'float': True, 'maxheight': 0, 'maxwidth': 0}}, 'screen': {'key': {'tab': 'focus-rel 1'}}, 'color': {'92': 92, '63': 63, '209': 209, '81': 81, '113': 113, '144': 144, '167': 167, '243': 243, '17': 17, '65': 65, '164': 164, '22': 22, '74': 74, '253': 253, '204': 204, '142': 142, '31': 31, '213': 213, '104': 104, '85': 85, '51': 51, '114': 114, '143': 143, '91': 91, '4': 2, '183': 183, '21': 21, '75': 75, '80': 80, '108': 108, '229': 229, '172': 172, '41': 41, '96': 96, '129': 129, '251': 251, '88': 88, '180': 180, '159': 159, '15': 15, '182': 182, '195': 195, '90': 90, '28': 28, '177': 177, '46': 46, '158': 158, '102': 102, '35': 35, '225': 225, '203': 203, '69': 69, '176': 176, '34': 34, '249': 249, '11': 11, '239': 239, '252': 252, '116': 116, '236': 236, '246': 246, '192': 192, '95': 95, '56': 56, '10': 10, '93': 93, '154': 154, '47': 47, '223': 223, '168': 168, '248': 248, '42': 42, '139': 139, '62': 62, '86': 86, '157': 157, '169': 169, '94': 94, '109': 109, '59': 59, '181': 181, '153': 153, '68': 68, '132': 132, '115': 115, '214': 214, '171': 171, '70': 70, '40': 40, '9': 9, '72': 72, '32': 32, '122': 122, '174': 174, '165': 165, '8': 8, '241': 241, '173': 173, '30': 30, '48': 48, '103': 103, '208': 208, '145': 145, '50': 50, '18': 18, '89': 89, '202': 202, '149': 149, '24': 24, '25': 25, '71': 71, '107': 107, '247': 247, '191': 191, '64': 64, '12': 12, '184': 184, '235': 235, '147': 147, '66': 66, '19': 19, '128': 128, '156': 156, '146': 146, '118': 118, '126': 126, '123': 123, '207': 207, '170': 170, '194': 194, '240': 240, '14': 14, '38': 38, '185': 185, '163': 163, '112': 112, '43': 43, '110': 110, 'defbg': -1, '125': 125, '13': 13, '197': 197, '130': 130, '78': 78, '160': 160, '217': 217, '228': 228, '61': 61, '3': 4, '45': 45, 'deffg': -1, '55': 55, '100': 100, '212': 212, '205': 205, '200': 200, '1': 4, '201': 201, '83': 83, '33': 33, '135': 135, '84': 84, '97': 97, '127': 127, '148': 148, '29': 29, '155': 155, '49': 49, '98': 98, '26': 26, '222': 222, '244': 244, '87': 87, '73': 73, '16': 16, '196': 196, '193': 193, '106': 106, '237': 237, '99': 99, '131': 131, '150': 150, '219': 219, '117': 117, '227': 227, '120': 120, '7': 0, '20': 20, '151': 151, '216': 216, '206': 206, '44': 44, '220': 220, '121': 121, '179': 179, '162': 162, '175': 175, '190': 190, '218': 218, '141': 141, '211': 211, '82': 82, '134': 134, '124': 124, '224': 224, '226': 226, '133': 133, '221': 221, '234': 234, '210': 210, '39': 39, '52': 52, '53': 53, '119': 119, '105': 105, '250': 250, '199': 199, '255': 255, '233': 233, '152': 152, '36': 36, '188': 188, '198': 198, '79': 79, '77': 77, '178': 178, '138': 138, '0': 7, '166': 166, '76': 76, '6': {'bg': 1, 'fg': 7}, '58': 58, '2': 3, '238': 238, '101': 101, '161': 161, '67': 67, '37': 37, '111': 111, '242': 242, '140': 140, '245': 245, '254': 254, '215': 215, '27': 27, '136': 136, '5': 5, '60': 60, '189': 189, '137': 137, '57': 57, '187': 187, '23': 23, '232': 232, '230': 230, '186': 186, '54': 54, '231': 231}, 'tags': 'maintag:.*', 'input': {'window': {'align': 'bottom', 'border': 'none', 'float': False, 'maxheight': 0, 'maxwidth': 0}}, 'tagobj': {'unselected': '', 'selected_end': '%r', 'selected': '%R', 'unselected_end': '', 'format': '%?{sel}(%{selected}:%{unselected})%?{c}([+]:[-])%{pre} %t %{post} [%B%1%n%0%b]% %?{pending}([%8%B%{pending}%b%0]:)%?{sel}(%{selected_end}:%{unselected_end})'}, 'story': {'unselected': '', 'marked': '%B[*] ', 'unmarked_end': '', 'unread_end': '%b%0', 'format_attrs': ['title'], 'read': '%2', 'enumerated': False, 'marked_end': '%b', 'read_end': '%0', 'format': '%?{sel}(%{selected}:%{unselected})%?{m}(%{marked}:%{unmarked})%?{rd}(%{read}:%{unread})%{pre}%t%{post}%?{m}(%{marked_end}:%{unmarked_end})%?{rd}(%{read_end}:%{unread_end})%?{sel}(%{selected_end}:%{unselected_end})', 'unselected_end': '', 'selected_end': '%r', 'unread': '%1%B', 'selected': '%R', 'unmarked': ''}, 'infobox': {'key': {'h': 'item-state unread', 'l': 'item-state read', 'npage': 'page-down', 'up': 'scroll-up', 'space': 'destroy', 'ppage': 'page-up', 'down': 'scroll-down'}, 'window': {'align': 'topleft', 'border': 'full', 'float': True, 'maxheight': 0, 'maxwidth': 0}}, 'tagorder': ['maintag:Golem.de', 'maintag:Heise', 'maintag:Stuttmann', 'maintag:Techerator', 'maintag:Spiegel', 'maintag:BBC', 'maintag:Phoronix', 'maintag:Techdirt.', 'maintag:Pro-Linux', 'maintag:Planet Arch Linux', 'maintag:Planet Arch Linux De', 'maintag:Arch Linux Bugtracker::', 'maintag:Canto', 'maintag:BITblokes', 'maintag:Inconsolation', 'maintag:Motho ke motho ka botho', 'maintag:Neusprech', 'maintag:Niggemeier', 'maintag:Slate Star Codex', 'maintag:TekSec', 'maintag:Schneier on Security', 'maintag:Mostly signs (some portents)', 'maintag:The Legal Satyricon'], 'taglist': {'hide_empty_tags': True, 'border': False, 'window': {'align': 'neutral', 'border': 'none', 'float': False, 'maxheight': 0, 'maxwidth': 0}, 'tags_enumerated': False, 'cursor': {'edge': 5, 'scroll': 'scroll', 'type': 'edge'}, 'search_attributes': ['title'], 'tags_enumerated_absolute': False, 'key': {'up': 'rel-set-cursor -1', 'j': 'rel-set-cursor 1', 'E': 'toggle taglist.tags_enumerated', '/': 'search', 'R': 'item-state read *', 'k': 'rel-set-cursor -1', '$': 'item-state read t:. 0-.', 'down': 'rel-set-cursor 1', 'h': 'item-state -read', 'r': 'tag-state read', 'e': 'toggle story.enumerated', 'C-u': 'unset-cursor', 'ppage': 'page-up', 'c': 'toggle-collapse', 'l': 'item-state read', 'U': 'item-state -read *', 'u': 'tag-state -read', '?': 'search-regex', 'J': 'next-tag', 'space': 'foritem & item-state read & reader', '+': 'promote', 'g': 'foritems & goto & item-state read & clearitems', 'C': 'collapse *', 'p': 'prev-marked', 'n': 'next-marked', '-': 'demote', 'V': 'uncollapse *', 'K': 'prev-tag', 'npage': 'page-down', 'M': 'item-state -marked *'}}}

**Comment by themoken** [comment] 2015-06-19 17:02
Hey Narrat, I was able to reproduce the empty :del issue and I just pushed a fix for both curses and an issue I ran into with the daemon and the new thread limiting fetch. Anyway, let me know if that fixes it for you.

I wasn't able to get :add to screw up though, in the whole log (not just the SIGUSR1 output) are there Exceptions?

**Comment by Narrat** [comment] 2015-06-19 23:20
That's the weird thing. No exceptions at all in the log. But the curses interface is hanging like #20 and #21 but without the cpu jumping to 100%
I will try it some more (giving it some more time)

And will test the fixes

**Comment by Narrat** [comment] 2015-06-20 10:37
Ok, more time was needed. Let it running for a while and sometimes later the "popup" appeared that the feed got added.
One note though. Items from a newly added feed aren't removed by f5+filter_read in the same curses session where the feed got added

**Comment by themoken** [comment] 2015-06-20 20:25
F5 is bound to :update by default, which won't remove items, only add new ones. C-r (:refresh) will re-filter and re-sort everything. I should probably remove that distinction, but as of right now that's working as expected.

**Closed by themoken** 2015-06-20 20:25 UTC

**Comment by themoken** [comment] 2015-06-20 20:41
Actually, that was wrong, it should remove, just not reorder unless an option is set. I'll squash it, but I'll leave this bug closed since it's a new thing.

**Comment by themoken** [comment] 2015-06-20 21:00
Okay, just pushed a fix for F5 not refiltering after :adding . Thanks for the reports.
